### ISSUE TITLE
bug: luarocks installation failed

### ISSUE THREAD

**Issue by bzp2010** [szensk/luaxxhash#2]
We used the `git://` protocol in rockspec for cloning code repositories on GitHub, but according to [**this documentation**](https://github.blog/2021-09-01-improving-git-protocol-security-github/), GitHub will no longer support the use of this unencrypted and insecure git protocol, so an error will be generated when trying to install dependencies.

## Related code

https://github.com/szensk/luaxxhash/blob/7bcca4f6da3385ca43eb2e3378ae7a66762bb4df/releases/luaxxhash-1.0.0-1.rockspec#L4

## Error

![image](https://user-images.githubusercontent.com/8078418/148962512-8bb65d10-d1e3-4640-86c3-e5eff1a0f088.png)

**Comment by bzp2010** [comment]
Based on the changes in luarocks, perhaps we can set the protocol to `git+https://`.

https://github.com/luarocks/luarocks/blob/9ff512e35455939f02eaec2318e3acc77782fdeb/src/luarocks/fetch.lua#L505-L513

**Comment by szensk** [comment]
I updated the rockspec in luarocks. Can you try to install it again?

**Comment by bzp2010** [comment]
OK, I will try it and get back to you later.

**Comment by bzp2010** [comment]
After testing, it did fix it, and the current older version of luarocks (this issue was fixed by luarocks 3.8.0 using special case code) can install it normally now.

Thank you for your help!

BTW, I notice you add the rockspec `1.0.0-2`, bug there is a typo. `1.0.0-1` => `1.0.0-2`. If modifications are needed.

https://github.com/szensk/luaxxhash/blob/a4aaf3c66e24879fd5b6c3d1ca063d79cf27f07b/releases/luaxxhash-1.0.0-2.rockspec#L2

**Comment by szensk** [comment]
I was planning to do a revision to the spec, since the actual code hasn't changed.
