### ISSUE TITLE
Publish a .src.rock file to Luarocks.org for organizations with restrictive firewall rules.

### ISSUE THREAD

**Issue by joshua-kast** [szensk/luaxxhash#3]
Hello mainters of luaxxhash, 

The organization I work with uses several Lua libraries that depend on luaxxhash as a transitive dependency. Our organization has very restrictive outbound network access rules. This prevents resolving luaxxhash from github via either git or https.

Generally we source all of our third party dependencies from Artifactory. Artifactory, like other binary repositories, does not inherently support LuaRocks. Instead, we use a generic repository pointed at https://luarocks.org/. This works fine for packages with .src.rock files. However, packages posted to https://luarocks.org/ that do not have .src.rock files will generally have issues.

If possible, could you please upload a .src.rock file of the project to https://luarocks.org/? According to LuaRock's documentation this is supposed to occur when a package is submitted to LuaRocks, but I suspect this is not the case for older packages. https://github.com/luarocks/luarocks/wiki/Creating-a-rock#method-1-using-a-repository-such-as-github

My read of the documentation is that uploading a .src.rock should be easy. You just need to package this repo and post it using this command: https://github.com/luarocks/luarocks/wiki/Creating-a-rock#upload-command.

Thank you! I understand your time is valuable. If you get around to this, I am happy to donate $50 dollars to a charity of your choice. You will have saved me so much time it would absolutely be worth it.

**Comment by szensk** [comment]
@joshua-kast I have added the src rock. Please let me know if this works for your purposes.

**Comment by joshua-kast** [comment]
Thanks Jon. Feel free to nominate a charity and I'll send you a screenshot of the reciept.

**Comment by szensk** [comment]
https://www.habitat.org/
Thanks for your generosity

**Comment by joshua-kast** [comment]
![image](https://user-images.githubusercontent.com/84940407/215620319-3d2ec8d5-2db8-409d-aee0-6aa27b648951.png)
 
You are very welcome Jon.
